env_name          : 'sawyer_door-v0'
n_episodes        : 100
max_ep_length     : 75
seed              : 123
base_action       : 'null'
render            : False
job_mode          : 'sweep'
exp_notes         : '7-DOF Sawyer arm opening a door at different locations'

########Re-tuned########
random_shooting:
  horizon           : 16
  init_cov          : 0.25
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  num_cpu           : 10
  particles_per_cpu : 12

mppi:
  horizon           : 16
  init_cov          : 0.9
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  lam               : 0.15
  alpha             : 1
  num_cpu           : 10
  particles_per_cpu : 12

cem:
  horizon           : 16
  init_cov          : 0.35
  cov_type          : 'full'
  beta              : 0.25
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  elite_frac        : 0.1
  num_cpu           : 10
  particles_per_cpu : 12

dmd:
  horizon           : 16
  init_cov          : 0.9
  update_cov        : True
  cov_type          : 'full'
  beta              : 0.25
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 0.6
  lam               : 0.15
  num_cpu           : 10
  particles_per_cpu : 12


pfmpc:
  horizon           : 16
  cov_shift         : 0.8
  cov_resample      : 1.0
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  lam               : 0.1
  num_cpu           : 10
  particles_per_cpu : 12


#Tuned
# random_shooting:
#   horizon           : 16
#   init_cov          : 0.25
#   filter_coeffs     : [0.25, 0.8, 0.0]
#   gamma             : 1.0
#   n_iters           : 1
#   step_size         : 1.0
#   num_cpu           : 10
#   particles_per_cpu : 12

# mppi:
#   horizon           : 16
#   init_cov          : 0.3
#   filter_coeffs     : [0.25, 0.8, 0.0]
#   gamma             : 1.0
#   n_iters           : 1
#   step_size         : 1.0
#   lam               : 0.45
#   alpha             : 1
#   num_cpu           : 10
#   particles_per_cpu : 12